#define 	PJMEDIA_CODEC_L16_HAS_8KHZ_MONO   1
#define 	PJMEDIA_CODEC_L16_HAS_8KHZ_STEREO   1
#define 	PJMEDIA_CODEC_L16_HAS_16KHZ_MONO   1
#define 	PJMEDIA_CODEC_L16_HAS_16KHZ_STEREO   1
#define 	PJMEDIA_CODEC_L16_HAS_48KHZ_MONO   1
#define 	PJMEDIA_CODEC_L16_HAS_48KHZ_STEREO   1


#define 	PJMEDIA_CODEC_OPUS_DEFAULT_BIT_RATE   128000
#define 	PJMEDIA_CODEC_OPUS_DEFAULT_COMPLEXITY   10
#define 	PJMEDIA_CODEC_OPUS_DEFAULT_CBR   PJ_TRUE

 
#define  	PJMEDIA_CONF_USE_AGC   0
#define 	PJMEDIA_SPEEX_AEC_USE_AGC   0


#define 	PJSUA_MAX_CALLS			255

#define PJMEDIA_AUDIO_DEV_HAS_ALSA		1
#undef PJMEDIA_AUDIO_DEV_HAS_PORTAUDIO
#define PJMEDIA_AUDIO_DEV_HAS_PORTAUDIO		0
